[CDAP-16323] Added field name to DB source exception messages
cdapio/hydrator-plugins pull request #1033
Opened 2020-03-07 02:02 UTC by vravish

2020-03-07 09:31 UTC, bdmogal requested changes
@vravish minor suggestion to improve the grammar. Are these the only instances where this needs to be fixed?

2020-03-07 09:31 UTC, bdmogal commented on database-plugins/src/main/java/io/cdap/plugin/DBRecord.java
> +        throw new IOException(String.format("Unsupported datatype: %s with value: %s and name: %s.", fieldType, fieldValue, field.getName()));
I think we should fix the grammar in this sentence. How about - `Column %s with value %s has an unsupported datatype %s`.

2020-03-07 09:31 UTC, bdmogal commented on database-plugins/src/main/java/io/cdap/plugin/DBRecord.java
> +        throw new SQLException(String.format("Unsupported datatype: %s with value: %s and name: %s.", fieldType, fieldValue, field.getName()));
ditto

2020-03-10 00:24 UTC, vravish commented
@bdmogal Yes these are the only DB source exception messages. Please let me know if I missed any

2020-03-12 10:11 UTC, bdmogal approved these changes

2020-03-14 01:08 UTC, merged