[PLUGIN-1795] Override Array Max (Apache Poi) for large files
cdapio/hydrator-plugins pull request #1873
Opened 2024-07-08 04:55 UTC by psainics

## Override Array Max (Apache Poi) for large files

Jira : [PLUGIN-1795](https://cdap.atlassian.net/browse/PLUGIN-1795)

### Description

A soft limit in set in apache poi to avoid OOM errors cause issue when working with large files.
This PR overrides the array max.

2024-07-17 12:25 UTC, itsankit-google requested changes
What is the soft limit in apache POI by default? 

How did we came up with this limit?

2024-07-17 12:38 UTC, psainics commented
> What is the soft limit in apache POI by default?

Apache poi uses `IOUtils.safelyAllocate` to allocate array of different size, the max len for each array is different based on the type of object.

[Check the code](https://github.com/search?q=repo%3Aapache%2Fpoi%20IOUtils.safelyAllocate&type=code)

int the logs i got `maximum length for this record type is 5,000,000`

 
> How did we came up with this limit?

As we cannot predict the size of file given by user i just wanted to set a big enough number.
INT_MAX / 2 is randomly selected, it looks big enough.

Info on the function [setByteArrayMaxOverride](https://poi.apache.org/components/configuration.html)

2024-07-19 18:28 UTC, itsankit-google commented
> > What is the soft limit in apache POI by default?
> 
> Apache poi uses `IOUtils.safelyAllocate` to allocate array of different size, the max len for each array is different based on the type of object.
> 
> [Check the code](https://github.com/search?q=repo%3Aapache%2Fpoi%20IOUtils.safelyAllocate&type=code)
> 
> int the logs i got `maximum length for this record type is 5,000,000`
> 
> > How did we came up with this limit?
> 
> As we cannot predict the size of file given by user i just wanted to set a big enough number. INT_MAX / 2 is randomly selected, it looks big enough.
> 
> Info on the function [setByteArrayMaxOverride](https://poi.apache.org/components/configuration.html)

What tests were performed to decide on this value?

2024-07-22 06:15 UTC, psainics commented
> 
> What tests were performed to decide on this value?

We wanted a value bigger than the current default, INT_MAX / 2 is taken as this is a much larger number than the default and it's unlikely any user will hit this limit.

A sanity test was performed by testing a file with similar size used by the user, which failed on the old build with the same error as expected but with the current patch applied the pipeline ran successfully !

2024-07-22 06:22 UTC, itsankit-google commented
> > What tests were performed to decide on this value?
> 
> We wanted a value bigger than the current default, INT_MAX / 2 is taken as this is a much larger number than the default and it's unlikely any user will hit this limit.
> 
> A sanity test was performed by testing a file with similar size used by the user, which failed on the old build with the same error as expected but with the current patch applied the pipeline ran successfully !

What was the file size used by the user? And did we test with files of size larger than that? Why not `INT_MAX` then?

2024-07-22 06:49 UTC, psainics commented
> > > What tests were performed to decide on this value?
> > 
> > 
> > We wanted a value bigger than the current default, INT_MAX / 2 is taken as this is a much larger number than the default and it's unlikely any user will hit this limit.
> > A sanity test was performed by testing a file with similar size used by the user, which failed on the old build with the same error as expected but with the current patch applied the pipeline ran successfully !
> 
> What was the file size used by the user? And did we test with files of size larger than that? Why not `INT_MAX` then?

The file size used by user was `150MB` 
We have tested for files around that size, not more than this. 

I did not take INT_MAX as per [this post](https://stackoverflow.com/questions/3038392/do-java-arrays-have-a-maximum-size) , INT_MAX is more than the limit of array you can allocate, there could be more ` + padding ` when allocating array , so it's better to take a value less than INT_MAX, i settled on INT_MAX / 2

2024-07-22 06:55 UTC, itsankit-google commented
> > > > What tests were performed to decide on this value?
> > > 
> > > 
> > > We wanted a value bigger than the current default, INT_MAX / 2 is taken as this is a much larger number than the default and it's unlikely any user will hit this limit.
> > > A sanity test was performed by testing a file with similar size used by the user, which failed on the old build with the same error as expected but with the current patch applied the pipeline ran successfully !
> > 
> > 
> > What was the file size used by the user? And did we test with files of size larger than that? Why not `INT_MAX` then?
> 
> The file size used by user was `150MB` We have tested for files around that size, not more than this.
> 
> I did not take INT_MAX as per [this post](https://stackoverflow.com/questions/3038392/do-java-arrays-have-a-maximum-size) , INT_MAX is more than the limit of array you can allocate, there could be more `+ padding` when allocating array , so it's better to take a value less than INT_MAX, i settled on INT_MAX / 2

It might be okay to use `INT_MAX/2` by default if it works with files around 1GB size. Please test this once, also provide a way for users to change this via runtime argument in future.

2024-08-07 07:18 UTC, psainics commented
Add ability to override the `byteArrayMaxOverride` with the runtime argument `excel.byteArrayMaxOverride`

2024-08-07 07:27 UTC, itsankit-google approved these changes

2024-08-07 09:42 UTC, merged