Feature/hydra 976 compression options
cdapio/hydrator-plugins pull request #479
Opened 2016-09-27 14:33 UTC by russorat

Adding compression options to hdfs sinks.

2016-10-10 20:35 UTC, nitinmotgi requested changes
Few minor comments. Please address them.

2016-10-10 20:35 UTC, nitinmotgi commented on core-plugins/src/main/java/co/cask/hydrator/plugin/batch/sink/S3AvroBatchSink.java
> +      if (config.compressionCodec != null && !config.compressionCodec.equals("None")) {
Can we ignore case when we check for 'None'.

2016-10-10 20:35 UTC, nitinmotgi commented on core-plugins/src/main/java/co/cask/hydrator/plugin/batch/sink/S3AvroBatchSink.java
> +        conf.put("mapred.output.compress", "true");
Can we put "mapred.output.compress" and such in a static variable at the top of the class.

2016-10-10 20:35 UTC, nitinmotgi commented on core-plugins/src/main/java/co/cask/hydrator/plugin/batch/sink/SnapshotFileBatchParquetSink.java
> +          propertiesBuilder.setOutputProperty("parquet.compression", "SNAPPY");
Same here!!

2016-10-10 20:35 UTC, nitinmotgi commented on core-plugins/src/main/java/co/cask/hydrator/plugin/batch/sink/SnapshotFileBatchParquetSink.java
> +          propertiesBuilder.setOutputProperty("parquet.compression", "GZIP");
Same here

2016-10-10 20:35 UTC, nitinmotgi commented on core-plugins/src/main/java/co/cask/hydrator/plugin/batch/sink/SnapshotFileBatchParquetSink.java
> +          propertiesBuilder.setOutputProperty("parquet.compression", "LZO");
Same here

2016-10-10 20:35 UTC, nitinmotgi commented on core-plugins/src/main/java/co/cask/hydrator/plugin/batch/sink/TimePartitionedFileSetDataSetORCSink.java
> +      LOG.info("Config: {}", config);
remove INFO log.

2016-10-10 20:35 UTC, nitinmotgi commented on core-plugins/src/test/java/co/cask/hydrator/plugin/batch/ETLBatchTestBase.java
> + * Copyright © 2016 Cask Data, Inc.
2015, 2016

2016-10-10 20:35 UTC, nitinmotgi commented on core-plugins/src/main/java/co/cask/hydrator/plugin/batch/sink/TimePartitionedFileSetSink.java
> + * Copyright © 2016 Cask Data, Inc.
2015, 2016

2016-10-10 20:35 UTC, nitinmotgi commented on core-plugins/src/main/java/co/cask/hydrator/plugin/batch/sink/TimePartitionedFileSetDatasetAvroSink.java
> + * Copyright © 2016 Cask Data, Inc.
2015, 2016

2016-10-10 20:35 UTC, nitinmotgi commented on core-plugins/src/main/java/co/cask/hydrator/plugin/batch/sink/SnapshotFileBatchAvroSink.java
> + * Copyright © 2016 Cask Data, Inc.
2015, 2016

2016-10-10 20:35 UTC, nitinmotgi commented on core-plugins/src/main/java/co/cask/hydrator/plugin/batch/sink/S3AvroBatchSink.java
> + * Copyright © 2016 Cask Data, Inc.
2015, 2016

2016-10-10 20:35 UTC, nitinmotgi commented on core-plugins/src/main/java/co/cask/hydrator/plugin/batch/sink/TimePartitionedFileSetDatasetParquetSink.java
> +        case "Snappy":
This code is being repeated, could we centralize this.

2016-10-10 20:35 UTC, nitinmotgi commented on core-plugins/src/test/java/co/cask/hydrator/plugin/batch/ETLTPFSTestRun.java
> + * Copyright © 2016 Cask Data, Inc.
2015, 2016

2016-10-10 20:35 UTC, nitinmotgi commented on core-plugins/src/test/java/co/cask/hydrator/plugin/batch/ETLBatchTestBase.java
> +  protected boolean checkFileType(TimePartitionedFileSet fileSet, String expectedType) throws IOException {
This is not generic and wouldn't be able to handle the time partition specification.

2016-10-10 20:35 UTC, nitinmotgi commented on core-plugins/src/test/java/co/cask/hydrator/plugin/batch/sink/S3BatchSinkTest.java
> + * Copyright © 2016 Cask Data, Inc.
2015, 2016

2016-10-10 20:35 UTC, nitinmotgi commented on hdfs-plugins/src/main/java/co/cask/hydrator/plugin/HDFSSink.java
> + * Copyright © 2016 Cask Data, Inc.
2015, 2016

2016-10-10 20:35 UTC, nitinmotgi commented on hdfs-plugins/src/test/java/co/cask/hydrator/plugin/HDFSSinkTest.java
> + * Copyright © 2016 Cask Data, Inc.
2015, 2016

2016-12-08 23:32 UTC, russorat commented
closing in favor of new PR

2016-12-08 23:32 UTC, closed without merging