[HYDRATOR-1002] Converted Rows limit input widget type from number to textbox in excel plugin.
cdapio/hydrator-plugins pull request #493
Opened 2016-10-21 10:50 UTC by romy-khetan

2016-10-25 18:51 UTC, abhinavbansal246 requested changes

2016-10-25 18:51 UTC, abhinavbansal246 commented on core-plugins/src/main/java/co/cask/hydrator/plugin/batch/source/ExcelInputReader.java
> +      if (!containsMacro("rowsLimit") && !StringUtils.isNumeric(rowsLimit)) {
This might fail as isNumeric returns true for empty string based on what version of apache commons you are using.

2016-10-25 18:51 UTC, abhinavbansal246 commented on core-plugins/src/main/java/co/cask/hydrator/plugin/batch/source/ExcelInputReader.java
> +      if (!containsMacro("rowsLimit") && !StringUtils.isNumeric(rowsLimit)) {
Add a unit test for this check

2016-10-25 18:51 UTC, abhinavbansal246 commented on core-plugins/src/main/java/co/cask/hydrator/plugin/batch/source/ExcelInputReader.java
>      }
What happens if user gives string as a runtime argument using macro?

2016-10-25 18:51 UTC, abhinavbansal246 commented on core-plugins/src/main/java/co/cask/hydrator/plugin/batch/source/ExcelInputReader.java
> +        throw new IllegalArgumentException("Invalid row limit. The value should be greater than zero.");
incorrect message should be something like this
String.format("Invalid row limit, numeric value expected. value provided = {}", rowLimit)

2016-10-26 13:11 UTC, romy-khetan commented
@abhinavbansal246 
Updated PR with review comments. Please review.

2016-10-28 01:19 UTC, abhinavbansal246 commented
LGTM

2016-10-28 20:45 UTC, abhinavbansal246 commented
Please squash the commits, Paste last 20 lines of ITN and verify by running on a cluster

2016-11-02 10:37 UTC, romy-khetan commented
@abhinavbansal246
Squashed the commits. However, due to FileSet issues in Excel Reader plugin, tests including ITN tests has been ignored until the issue is resolved. Although verified the fix through creating pipeline in the cluster using UI.

2016-11-02 17:31 UTC, abhinavbansal246 approved these changes

2016-11-02 17:31 UTC, merged