HYDRATOR 471 - conditions clause is excluded from the query in get schema request in database source
cdapio/hydrator-plugins pull request #522
Opened 2016-11-28 08:53 UTC by shashankmoghe

Tested from UI
If use enters $CONDITIONS in the query,though it would be visible in the UI,internally back end logic would exclude the $CONDITIONS clause and execute the manipulated query.

2016-11-30 05:09 UTC, nitinmotgi requested changes

2016-11-30 05:09 UTC, nitinmotgi commented on database-plugins/src/main/java/co/cask/hydrator/plugin/db/batch/source/DBSource.java
> +    if (importQuerySring.toUpperCase().contains("WHERE $CONDITIONS AND")) {
What happens if there are two spaces between $CONDITIONS and AND. Can you please make this robust.

2016-11-30 05:09 UTC, nitinmotgi commented on database-plugins/src/main/java/co/cask/hydrator/plugin/db/batch/source/DBSource.java
> +    } else if (importQuerySring.toUpperCase().contains("AND $CONDITIONS")) {
overall this method is fragile. Could you please make it robust.

2016-12-02 10:20 UTC, shashankmoghe commented
Closing this PR and will open a new PR against release/1.5

2016-12-02 10:20 UTC, closed without merging