HYDRATOR-1498 Make transaction isolation level configurable
cdapio/hydrator-plugins pull request #645
Opened 2017-04-25 22:05 UTC by Denton-L

JIRA: https://issues.cask.co/browse/HYDRATOR-1498

2017-04-25 23:23 UTC, nitinmotgi commented on database-plugins/widgets/Database-batchsource.json
> +              "TRANSACTION_NONE",
Not user friendly !!!

2017-04-25 23:24 UTC, nitinmotgi requested changes
Can you please make it user friendly.

2017-04-25 23:24 UTC, Denton-L commented on database-plugins/widgets/Database-batchsource.json
> +              "TRANSACTION_NONE",
What would a good alternative be?

2017-04-25 23:26 UTC, Denton-L commented on database-plugins/widgets/Database-batchsource.json
> +              "TRANSACTION_NONE",
It's all selected from a dropdown menu so the user shouldn't have to enter anything manually.

2017-04-25 23:33 UTC, gsps1 commented
will be good to update the docs about this property `Database-batchsource.md`

2017-04-26 18:11 UTC, Denton-L commented
@nitinmotgi Updated it to make it more user-friendly.

2017-05-16 19:21 UTC, awholegunch commented
Docs LGTM, but someone else should check my changes.

2017-06-06 00:42 UTC, closed without merging